server:
  port: 8080  # Backend will run here

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/studentdb
    username: student
    password: studentpwd

  jpa:
    hibernate:
      ddl-auto: none  # Let Flyway handle schema
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
