# application.yml
spring:
  application:
    name: student-enrollment-api

  datasource:
    url: jdbc:postgresql://localhost:5432/student_db
    username: student_app
    password: studentpwd
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8081  # change to 8081 if 8080 is busy

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
